version: '3'
services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"  # Port 80  container HAProxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg  #  HAProxy
    networks:
      - lb-net
  server1:
    image: nginxdemos/hello
    container_name: server1
    environment:
      - SERVER_NAME=Server1
    ports:
      - "8081:80"
    networks:
      - lb-net

  server2:
    image: nginxdemos/hello
    container_name: server2
    environment:
      - SERVER_NAME=Server2
    ports:
      - "8082:80"
    networks:
      - lb-net

networks:
  lb-net:
    driver: bridge 